/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2024.1.0.34.2
    Soft IP Version: 2.0.0
    2024 12 02 14:38:19
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module SB_MAC16 (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [15:0]  data_a_i;
    input  [15:0]  data_b_i;
    output  [32:0]  result_o;
endmodule